### ISSUE TITLE
Tube injection limit too low?

### ISSUE THREAD

**Issue by S-S-X** [minetest-monitoring/monitoring_pipeworks#2]
I have feeling 20 stacks / second seems bit low and probably making more harm than good.

While it wont prevent long high stack count loops in tubes it will still cause significant item loss with many systems.

I see this limit tries to address pipeworks issues on pandorabox but it is not actually guarding against that exact issue very well (which apparently was tp tube loop combined with other issues) and causes other problems (destroying stacks).

**Comment by S-S-X** [comment]
So while simple honey farm that triggers breakers about twice / hour and apparently tree farms will lose expensive items very fast still very simple "lag device" I built seems to generate near 400ms workload while not getting even near limits. Most of time staying between 3 - 6 / max 20.

Also lag machine did that without losing single stack. But not only that, concept is simple enough that one could build such machine by just making simple configuration mistake.

**Comment by BuckarooBanzay** [comment]
i've increased the limit to 100 for now, the amount of items that got trashed is here: https://monitoring.minetest.land/d/B37ILXmZk/pipeworks?orgId=1&refresh=5s&from=now-24h&to=now on the upper left as "Blocked entities"

> Also lag machine did that without losing single stack. But not only that, concept is simple enough that one could build such machine by just making simple configuration mistake.

Did you manage to find that machine??

**Comment by S-S-X** [comment]
I found good candidate which was clearly simple configuration mistake with tp tubes.
Also built simple small machine with 12 tp tubes and some accelerator tubes, visible here:
![image](https://user-images.githubusercontent.com/50966843/111029941-3fcdf880-8408-11eb-9e8b-3b9f9e8717c9.png)
And like said that is just for 12 tp tubes and one of those leading to material storage.

Inject limits were jumping mostly between 3-6 while 12 tube machine was running.

Actual machine with tube config fault had few hundred tp tubes and only single way out.
